db-move: moved aarch64-linux-gnu-binutils from [community-testing] to [community] (i686, x86_64)
git-svn-id: file:///srv/repos/svn-community/svn@201147 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/aarch64-linux-gnu-binutils/repos/community-x86_64/PKGBUILD b/aarch64-linux-gnu-binutils/repos/community-x86_64/PKGBUILD
--- a/aarch64-linux-gnu-binutils/repos/community-x86_64/PKGBUILD
+++ b/aarch64-linux-gnu-binutils/repos/community-x86_64/PKGBUILD
@@ -4,7 +4,7 @@
 _target=aarch64-linux-gnu
 pkgname=$_target-binutils
 pkgver=2.27
-pkgrel=1
+pkgrel=2
 #_commit=2bd25930
 pkgdesc='A set of programs to assemble and manipulate binary and object files for the ARM64 target'
 arch=(i686 x86_64)
@@ -24,6 +24,12 @@ prepare() {
 build() {
   cd binutils-$pkgver
 
+  if [ "${CARCH}" != "i686" ];
+  then
+    # enabling gold linker at i686 makes the install fail
+    enable_gold='--enable-gold'
+  fi
+
   ./configure --target=$_target \
               --with-sysroot=/usr/$_target \
               --prefix=/usr \
@@ -31,7 +37,10 @@ build() {
               --with-gnu-as \
               --with-gnu-ld \
               --disable-nls \
-              --enable-plugins
+              --enable-ld=default \
+              $enable_gold \
+              --enable-plugins \
+              --enable-deterministic-archives
 
   make
 }
@@ -41,7 +50,7 @@ check() {
   
   # unset LDFLAGS as testsuite makes assumptions about which ones are active
   # do not abort on errors - manually check log files
-  make LDFLAGS="" -k check
+  make -k LDFLAGS="" check || true
 }
 
 package() {
