git-svn-id: file:///srv/repos/svn-community/svn@15543 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/xbmc/trunk/PKGBUILD b/xbmc/trunk/PKGBUILD
--- a/xbmc/trunk/PKGBUILD
+++ b/xbmc/trunk/PKGBUILD
@@ -7,46 +7,45 @@ _ext_python="disable"
 
 pkgname=xbmc
 pkgver=9.11
-pkgrel=11
+pkgrel=17
 pkgdesc="XBMC Media Center"
 arch=('i686' 'x86_64')
 url="http://xbmc.org"
 license=('GPL' 'custom')
-depends=('alsa-lib' 'curl' 'enca' 'faac' 'freetype2' 'fribidi' 'gawk' 'glew'
-         'hal' 'jasper' 'libgl' 'libjpeg>=7' 'libmad' 'libmysqlclient' 'ffmpeg'
-         'libxinerama' 'libxrandr' 'lzo2' 'sdl_image>=1.2.10' 'sdl_mixer' 'sqlite3'
-         'tre' 'unzip' 'xorg-server' 'libcdio' 'wavpack' 'libmpeg2' 'a52dec'
-         'libdca' 'smbclient' 'faad2' 'libsamplerate' 'libmms' 'xorg-utils')
+depends=( 'bzip2' 'curl' 'enca' 'faac' 'faad2' 'fontconfig' 'fribidi'
+          'glew' 'hal' 'jasper' 'libcdio' 'libgl' 'libmad' 'libmms'
+		  'libmpeg2' 'libmysqlclient' 'libsamplerate' 'libxinerama'
+		  'libxrandr' 'libxtst' 'lzo2' 'sdl_image' 'sdl_mixer' 
+		  'smbclient' 'wavpack' )
 if [ "$_ext_python" != "disable" ]; then
   depends=( '${depends[@]}' 'python' )
 fi
-makedepends=('autoconf' 'automake' 'boost' 'cmake' 'gcc' 'gperf'
-            'libtool>=2.2.6a-1' 'make' 'nasm' 'patch' 'pkgconfig' 'zip'
-            'libvdpau')
+makedepends=('boost' 'cmake' 'gperf' 'nasm' 'libvdpau' 'unzip' 'zip')
 optdepends=('lirc: remote controller support'
-	    'smbclient: access windows shares'
-	    'unrar: access compressed files without unpacking them'
-	    'devicekit-power: used to trigger suspend functionality')
-install=${pkgname}.install
-options=(force)
-source=(http://downloads.sourceforge.net/project/xbmc/XBMC%20Source%20Code/Camelot%20-%20$pkgver/xbmc-${pkgver/_/-}.tar.gz
-        use_cdio_system_headers_on_non_win32.patch
-        FEH.sh libpng14.patch)
-md5sums=('9a68ac1e2f44a54cc3803fcdb1265767'
-        '7b7403cdde791330b5ab70697d2054f2'
-        '0aa669eebaaf2a9f6e000e1f43869a7b'
-	'3f93cfc8aa21723ca3246dc5f9122177')
+            'unrar: access compressed files without unpacking them'
+            'devicekit-power: used to trigger suspend functionality')
+install=("${pkgname}.install")
+options=(makeflags)
+source=("http://downloads.sourceforge.net/project/xbmc/XBMC%20Source%20Code/Camelot%20-%20$pkgver/xbmc-${pkgver/_/-}.tar.gz"
+        "use_cdio_system_headers_on_non_win32.patch"
+        "FEH.sh"
+        "libpng14.patch"
+		"xbmc-9.11-wavpack.patch"
+)
 
 build() {
   cd "${srcdir}/xbmc-${pkgver/_/-}"
-  _xbmcprefix=/usr
-  patch -N -p1 -i  ../use_cdio_system_headers_on_non_win32.patch || return 1
+  msg "fix libcdio faults"
+  patch -N -p1 -i  ${srcdir}/use_cdio_system_headers_on_non_win32.patch || return 1
+  msg "fix libpng 1.4 problems"
   patch -Np1 -i ${srcdir}/libpng14.patch || return 1
-  # fix lsb_release dependency
+  msg "fix wavpack builderror"
+  patch -Np1 -i ${srcdir}/xbmc-9.11-wavpack.patch || return 1
+  msg "fix lsb_release dependency"
   sed -i -e 's:/usr/bin/lsb_release -d:cat /etc/arch-release:' xbmc/utils/SystemInfo.cpp || return 1
-  # fix faulty declaration in DllLaoder wrapper
+  msg "fix faulty declaration in DllLaoder wrapper"
   sed -i 's: ftell64: dll_ftell64:' xbmc/cores/DllLoader/exports/wrapper.c || return 1
-  # fix libjpeg7 delays
+  msg "fix libjpeg7 delays"
   sed -i 's|cinfo.scale_denom = GetJpegScale();|cinfo.scale_denom = GetJpegScale(); cinfo.scale_num = 1;|' xbmc/lib/cximage-6.0/CxImage/ximajpg.cpp || return 1
 
   if [ $NOEXTRACT -ne 1 ]; then
@@ -54,11 +53,11 @@ build() {
     export SVN_REV="-ARCH"
 
     ./bootstrap
-    ./configure --prefix=${_xbmcprefix} \
+    ./configure --prefix=/usr \
     --enable-vdpau \
     --disable-pulse \
     --disable-avahi \
-    --enable-external-liba52 \
+    --disable-external-liba52 \
     --disable-external-libdts \
     --enable-external-libmpeg2 \
     --enable-external-libogg \
@@ -70,48 +69,56 @@ build() {
   fi
 
   make || return 1
-  make prefix=${pkgdir}${_xbmcprefix} install || return 1
+}
+
+package() {
+  cd "${srcdir}/xbmc-${pkgver/_/-}"
+  make prefix=${pkgdir}/usr install || return 1
 
   # Fix the shell script
-  sed -i '3iexport SDL_AUDIODRIVER=alsa' ${pkgdir}${_xbmcprefix}/bin/xbmc
+  # sed -i '3iexport SDL_AUDIODRIVER=alsa' ${pkgdir}/usr/bin/xbmc
 
-  # if disabled external python install bash script and fix startup script
+  msg "bin/xbmc mods for arch package"
+  sed -i -e 's/which lsb_release &> \/dev\/null/\[ -f \/etc\/arch-release ]/g' ${pkgdir}/usr/bin/xbmc || return 1
+  sed -i -e "s/lsb_release -a 2> \/dev\/null | sed -e 's\/\^\/    \/'/cat \/etc\/arch-release/g" ${pkgdir}/usr/bin/xbmc || return 1
+  sed -i -e 's/\/usr\/share\/xbmc/\/opt\/xbmc/' ${pkgdir}/usr/bin/xbmc || return 1
+
+  msg "if disabled external python install bash script and fix startup script"
   if [ "$_ext_python" = "disable" ]; then
     install -Dm755 ${srcdir}/FEH.sh \
-    ${pkgdir}${_xbmcprefix}/share/xbmc/FEH.sh || return 1
-    sed -i -e "s/python \\${_xbmcprefix}\/share\/xbmc\/FEH.py \"\$@\"/\\${_xbmcprefix}\/share\/xbmc\/FEH.sh/g" ${pkgdir}${_xbmcprefix}/bin/xbmc || return 1
+    ${pkgdir}/usr/share/xbmc/FEH.sh || return 1
+    sed -i -e "s/python \/opt\/xbmc\/FEH.py \"\$@\"/\/opt\/xbmc\/FEH.sh/g" ${pkgdir}/usr/bin/xbmc || return 1
   fi
 
-  # bin/xbmc lsb_release fix in xmbc startup script
-  sed -i -e 's/which lsb_release &> \/dev\/null/\[ -f \/etc\/arch-release ]/g' ${pkgdir}${_xbmcprefix}/bin/xbmc || return 1
-  sed -i -e "s/lsb_release -a 2> \/dev\/null | sed -e 's\/\^\/    \/'/cat \/etc\/arch-release/g" ${pkgdir}${_xbmcprefix}/bin/xbmc || return 1
-
-  # Menu item
-  install -Dm644 ${srcdir}/xbmc-${pkgver/_/-}/tools/Linux/xbmc.desktop \
-  ${pkgdir}/usr/share/applications/xbmc.desktop || return 1
-  install -Dm644 ${srcdir}/xbmc-${pkgver/_/-}/tools/Linux/xbmc.png \
-  ${pkgdir}/usr/share/pixmaps/xbmc.png || return 1
-
-  # XBMCTex
-  #    install -Dm755 ${srcdir}/xbmc-${pkgver/_/-}/tools/XBMCTex/XBMCTex \
-  #                   ${pkgdir}${_xbmcprefix}/share/xbmc/tools/xbmctex || return 1
-
   # License(s)
+  msg "copy licences"
   install -dm755 ${pkgdir}/usr/share/licenses/${pkgname}
   for licensef in LICENSE.GPL README.linux copying.txt; do
-    mv ${pkgdir}${_xbmcprefix}/share/xbmc/${licensef} \
+    mv ${pkgdir}/usr/share/xbmc/${licensef} \
     ${pkgdir}/usr/share/licenses/${pkgname} || return 1
   done
 
-  # profile.d
-  mkdir -p $pkgdir/etc/profile.d/ && \
-  echo "export PATH=\$PATH:${_xbmcprefix}/bin" >$pkgdir/etc/profile.d/xbmc.sh && \
-  chmod 0755 $pkgdir/etc/profile.d/xbmc.sh || return 1
+  # cleanup some stuff
+  msg "cleanup unneeded dirs"
+  rm -r ${pkgdir}/usr/share/xsessions
 
   # fix .desktop
-  sed -i "s#Exec=xbmc#Exec=${_xbmcprefix}/bin/xbmc#" $pkgdir/usr/share/xsessions/XBMC.desktop $pkgdir/usr/share/applications/xbmc.desktop || return 1
+  msg "fix .desktop"
+  sed -i "s#Exec=xbmc#Exec=/usr/bin/xbmc#" $pkgdir/usr/share/applications/xbmc.desktop || return 1
+
+  msg "Move Faulty xbmc dir to /opt"
+  mkdir $pkgdir/opt/
+  mv $pkgdir/usr/share/xbmc $pkgdir/opt
+
+  msg "Remove old PM3.HD skin"
+  rm -r ${pkgdir}/opt/xbmc/skin/PM3.HD || return 1
 
   # strip
+  msg "strip binaries"
   find $pkgdir -type f -exec strip {} \; >/dev/null 2>/dev/null
 }
-
+md5sums=('9a68ac1e2f44a54cc3803fcdb1265767'
+         '7b7403cdde791330b5ab70697d2054f2'
+         'c3e2ab79b9965f1a4a048275d5f222c4'
+         '3f93cfc8aa21723ca3246dc5f9122177'
+         '062c5f61cd3bb27de66c861fd2c79de1')
