archrelease: copy trunk to community-any
git-svn-id: file:///srv/repos/svn-community/svn@569995 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/python-oslo-concurrency/repos/community-any/PKGBUILD b/python-oslo-concurrency/repos/community-any/PKGBUILD
--- a/python-oslo-concurrency/repos/community-any/PKGBUILD
+++ b/python-oslo-concurrency/repos/community-any/PKGBUILD
@@ -4,7 +4,7 @@
 pkgbase=python-oslo-concurrency
 pkgname=(python-oslo-concurrency python2-oslo-concurrency)
 pkgver=4.0.0
-pkgrel=1
+pkgrel=2
 pkgdesc="OpenStack library for all concurrency-related code"
 arch=('any')
 url="https://pypi.python.org/pypi/oslo.concurrency/$pkgver"
@@ -12,16 +12,15 @@ license=('Apache')
 makedepends=('python-setuptools' 'python2-setuptools' 'python-pbr' 'python2-pbr' 'python-oslo-config'
              'python2-oslo-config' 'python-oslo-i18n' 'python2-oslo-i18n' 'python-oslo-utils'
              'python2-oslo-utils' 'python-fasteners' 'python2-fasteners' 'python2-enum34')
-checkdepends=('python-mock' 'python2-mock' 'python-oslotest' 'python2-oslotest' 'python-oslo-config'
-              'python2-oslo-config' 'python-eventlet' 'python2-eventlet')
+checkdepends=('python-mock' 'python-oslotest' 'python-oslo-config' 'python-eventlet')
 options=('!emptydirs')
 source=("$pkgbase-$pkgver.tar.gz::https://github.com/openstack/oslo.concurrency/archive/$pkgver.tar.gz")
 sha512sums=('d75d84d4ce27b7418e358e5b5fdf0015511aa2caaddfed38f9eb4d1fdb4635c7df348c6cafbad26b3a0b9af8b41df898450f050e8899c4659c81b63ef8dfb45c')
 
+export PBR_VERSION=$pkgver
+
 prepare() {
   cp -a oslo.concurrency-$pkgver{,-py2}
-
-  export PBR_VERSION=$pkgver
 }
 
 build() {
@@ -33,11 +32,8 @@ build() {
 }
 
 check() {
-  cd "$srcdir"/oslo.concurrency-$pkgver
-  stestr run || warning "1 failure about raising rlimit"
-
-  cd "$srcdir"/oslo.concurrency-$pkgver-py2
-  PYTHON=python2 stestr2 run || warning "1 failure about raising rlimit"
+  cd oslo.concurrency-$pkgver
+  stestr run || : # "1 failure about raising rlimit"
 }
 
 package_python-oslo-concurrency() {
