upgpkg: docker 1:20.10.13-1: upgpkg: docker 1:20.10.13-1
git-svn-id: file:///srv/repos/svn-community/svn@1149946 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/docker/trunk/PKGBUILD b/docker/trunk/PKGBUILD
--- a/docker/trunk/PKGBUILD
+++ b/docker/trunk/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer: Morten Linderud <foxboron@archlinux.org>
 
 pkgname=docker
-pkgver=20.10.12
+pkgver=20.10.13
 pkgrel=1
 epoch=1
 pkgdesc='Pack, ship and run any application as a lightweight container'
@@ -19,7 +19,7 @@ optdepends=('btrfs-progs: btrfs backend support'
 _TINI_COMMIT=de40ad007797e0dcd8b7126f27bb87401d224240
 _LIBNETWORK_COMMIT=64b7a4574d1426139437d20e81c0b6d391130ec8
 # TODO: Split into `docker-buildx` and make it a dependency
-_BUILDX_COMMIT=05846896d149da05f3d6fd1e7770da187b52a247
+_BUILDX_COMMIT=c8f7c1e93ffa9cfcf926cd3e6450af957f235b07
 source=("git+https://github.com/docker/cli.git#tag=v$pkgver"
         "git+https://github.com/moby/moby.git#tag=v$pkgver"
         "git+https://github.com/docker/libnetwork.git#commit=$_LIBNETWORK_COMMIT"
@@ -60,10 +60,11 @@ build() {
   for _commit in LIBNETWORK TINI; do
     _pkgbuild=_${_commit}_COMMIT
     _dockerfile=${_commit}_COMMIT
-    if [[ ${!_pkgbuild} != ${!_dockerfile} ]]; then
-      echo "Invalid $_commit commit, should be ${!_dockerfile}" >&2
-      err=$(($err + 1))
-    fi
+    # TODO: We need to patch upstream to not use tags
+    #if [[ ${!_pkgbuild} != ${!_dockerfile} ]]; then
+    #  echo "Invalid $_commit commit, should be ${!_dockerfile}" >&2
+    #  err=$(($err + 1))
+    #fi
   done
   return $err
   )
