upgpkg: tint2 0.11-7
git-svn-id: file:///srv/repos/svn-community/svn@107236 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/tint2/trunk/PKGBUILD b/tint2/trunk/PKGBUILD
--- a/tint2/trunk/PKGBUILD
+++ b/tint2/trunk/PKGBUILD
@@ -1,4 +1,5 @@
 # $Id$
+# Maintainer: Alexander Rødseth <rodseth@gmail.com>
 # Contributor: Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
 # Contributor: Blue Peppers <bluepeppers@archlinux.us>
 # Contributor: Stefan Husmann< stefan-husmann@t-online.de>
@@ -7,7 +8,7 @@ pkgname=tint2
 pkgver=0.11
 pkgrel=7
 pkgdesc='Basic, good-looking task manager for WMs'
-arch=('i686' 'x86_64')
+arch=('x86_64' 'i686')
 url='http://code.google.com/p/tint2/'
 license=('GPL2')
 conflicts=('ttm-svn' 'tint')
@@ -19,15 +20,12 @@ provides=('tint')
 source=("http://tint2.googlecode.com/files/tint2-$pkgver.tar.bz2"
         'add-power-now-support.patch'
         'clock.patch'
-        'graph.patch'
         'launcher_apps_dir-v2.patch'
         'src-task-align.patch'
         'zombie-fix.patch')
-
 md5sums=('6fc5731e7425125fa84a2add5cef4bff'
-         '6cfcad028f1bd2f69812167f5395f890'
+         '448beead6c9d44b864f99e08a027cb56'
          'bc0bab2979dacff551a97bdf2c2fdedc'
-         '2866ebde44be8d48efd1e59ded5c5534'
          '13218765dd684ae825967d3ffb4f4a75'
          'f0d7f51ec8dbf2e7b6bcca942f0fd6c0'
          'cdb83cd911e005a3529e5d1cd952a956')
@@ -35,24 +33,12 @@ md5sums=('6fc5731e7425125fa84a2add5cef4bff'
 prepare() {
   cd "$pkgname-$pkgver"
 
-  # making all the patches apply is a work in progress
-  for f in "$srcdir"/*.patch; do
+  # Applying all patches, even some that only applies partially.
+  # Tint2 works fine with these, but a new release from upstream would be nice.
+  for f in ../*.patch; do
+    echo -e "--- ${f##*/} ---\n"
+    patch -Np1 -i $f && echo "${f##*/} OK!" || echo "${f##*/} FAILED!"
     echo
-    echo "--- ${f##*/} ---"
-    echo
-    if [[ ${f##*/} == add-power-now-support.patch ]]; then
-      patch -Np2 -i $f && echo "${f##*/} OK!"
-    elif [[ ${f##*/} == src-task-align.patch ]]; then
-      continue
-    elif [[ ${f##*/} == launcher_apps_dir-v2.patch ]]; then
-      continue
-    elif [[ ${f##*/} == graph.patch ]]; then
-      continue
-    elif [[ ${f##*/} == clock.patch ]]; then
-      continue
-    else
-      patch -Np1 -i $f && echo "${f##*/} OK!"
-    fi
   done
 
   # python2 fix
@@ -67,13 +53,12 @@ build() {
   cd build
   cmake .. \
     -DCMAKE_INSTALL_PREFIX=/usr \
-    -DCMAKE_INSTALL_LIBDIR=lib \
     -DENABLE_TINT2CONF=0
   make 
 }
 
 package() {
-  make -C "$pkgname-$pkgver" DESTDIR="$pkgdir" install
+  make -C "$pkgname-$pkgver/build" DESTDIR="$pkgdir" install
 }
 
 # vim:set ts=2 sw=2 et:
