upgpkg: tint2 0.12.4-1
git-svn-id: file:///srv/repos/svn-community/svn@158705 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/tint2/trunk/PKGBUILD b/tint2/trunk/PKGBUILD
--- a/tint2/trunk/PKGBUILD
+++ b/tint2/trunk/PKGBUILD
@@ -5,7 +5,7 @@
 # Contributor: Stefan Husmann< stefan-husmann@t-online.de>
 
 pkgname=tint2
-pkgver=0.12.3
+pkgver=0.12.4
 pkgrel=1
 pkgdesc='Basic, good-looking task manager for WMs'
 arch=('x86_64' 'i686')
@@ -16,29 +16,24 @@ depends=('gtk2' 'imlib2' 'startup-notification')
 makedepends=('cmake' 'startup-notification' 'git' 'ninja')
 source=("$pkgname-$pkgver.tgz::https://gitlab.com/o9000/tint2/repository/archive.tar.gz?ref=$pkgver"
         'zombie-fix.patch')
-sha256sums=('7f1f7cdb8eecfaaac620589c327bf29def457a9d38cee587769c93aacd2a3e36'
+sha256sums=('68065a85eec6f4186c52adb48d9fdab2b1008df92e34380038739c146bb59f06'
             'a1e942ca3bef05885989f899c0eaaf63f538f7b84cb43d1517d5d39aa64a4ef9')
 
 prepare() {
   mv "$pkgname-$pkgver-"* "$pkgname"
   cd "$pkgname"
-
-  # Applying all available patches
-  for f in ../*.patch; do
-    echo -e "--- ${f##*/} ---"
-    patch -Np1 -i $f && echo "${f##*/} OK!" || echo "${f##*/} FAILED!"
-  done
+  patch -Np1 -i ../zombie-fix.patch \
+    && echo "${f##*/} OK!" \
+    || echo "${f##*/} FAILED!"
 }
 
 build() {
   cd "$pkgname"
 
-  # Generating Ninja project files
-  mkdir -p build && cd build
+  mkdir -p build
+  cd build
   cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_TINT2CONF=1 -G Ninja
-
-  # Compiling
-  ninja 
+  ninja
 }
 
 package() {
