db-move: moved sagemath from [community-testing] to [community] (x86_64)
git-svn-id: file:///srv/repos/svn-community/svn@319431 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/sagemath/repos/community-x86_64/sagemath-env.patch b/sagemath/repos/community-x86_64/sagemath-env.patch
--- a/sagemath/repos/community-x86_64/sagemath-env.patch
+++ b/sagemath/repos/community-x86_64/sagemath-env.patch
@@ -41,17 +41,45 @@
 -fi
 +NEW_SAGE_ROOT="/usr"
  
- # Display the Sage startup banner, used in src/bin/sage
- sage_banner() {
-@@ -185,6 +185,7 @@
+ 
+ # Don't execute the commands more than once for the same version of
+@@ -174,33 +174,9 @@
  export SAGE_ENV_SOURCED=$SAGE_ENV_VERSION
  
  export SAGE_ROOT="$NEW_SAGE_ROOT"
 +export SAGE_LOCAL='/usr'
++export SAGE_SCRIPTS_DIR='/usr/bin'
  
+-
+-# sage-env must know where the Sage's script files are.
+-# Note that SAGE_SCRIPTS_DIR is only used here, so it does not need to
+-# be exported.
+-if [ -z "$SAGE_SCRIPTS_DIR" ]; then
+-    if [ -n "$SAGE_LOCAL" ] && [ -f "$SAGE_LOCAL/bin/sage-env-config" ]; then
+-        SAGE_SCRIPTS_DIR="$SAGE_LOCAL/bin"
+-    elif [ -f "$SAGE_ROOT/src/bin/sage-env-config" ]; then
+-        SAGE_SCRIPTS_DIR="$SAGE_ROOT/src/bin"
+-    else
+-        echo >&2 "Error: You must set either the SAGE_LOCAL or SAGE_SCRIPTS_DIR environment variable to run this"
+-        return 1
+-    fi
+-elif [ ! -f "$SAGE_SCRIPTS_DIR/sage-env-config" ]; then
+-    echo >&2 "Error: SAGE_SCRIPTS_DIR is set to a bad value:"
+-    echo >&2 "SAGE_SCRIPTS_DIR=$SAGE_SCRIPTS_DIR"
+-    echo >&2 "You must correct it or erase it and rerun this script"
+-    return 1
+-fi
+-
+-# Set environment variables (like SAGE_LOCAL) depending on ./configure
+-. "$SAGE_SCRIPTS_DIR/sage-env-config"
+-if [ $? -ne 0 ]; then
+-    echo >&2 "Error: failed to source $SAGE_SCRIPTS_DIR/sage-env-config"
+-    return 1
+-fi
  
- # sage-env must know where the Sage's script files are.
-@@ -307,8 +307,9 @@
+ # The compilers are set in order of priority by
+ # 1) environment variables
+@@ -296,8 +296,9 @@
  export SAGE_EXTCODE="$SAGE_SHARE/sage/ext"
  export SAGE_SPKG_INST="$SAGE_LOCAL/var/lib/sage/installed"
  export SAGE_LOGS="$SAGE_ROOT/logs/pkgs"
@@ -63,7 +91,7 @@
  export SAGE_DOC="$SAGE_SHARE/doc/sage"
  
  if [ -z "${SAGE_ORIG_PATH_SET}" ]; then
-@@ -414,6 +414,9 @@
+@@ -403,6 +403,9 @@
      export SAGE_STARTUP_FILE
  fi
  
@@ -73,7 +101,7 @@
  if [ "$PYTHON_EGG_CACHE" = "" ]; then
      PYTHON_EGG_CACHE="$DOT_SAGE/.python-eggs"
      export PYTHON_EGG_CACHE
-@@ -499,7 +499,6 @@
+@@ -488,7 +488,6 @@
          fi
      fi
  fi
@@ -81,7 +109,7 @@
  
  PERL5LIB="$SAGE_LOCAL/lib/perl5:$PERL5LIB" && export PERL5LIB
  
-@@ -619,9 +619,6 @@
+@@ -608,9 +608,6 @@
      LD_LIBRARY_PATH="$SAGE_LOCAL/bin:$LD_LIBRARY_PATH" && export LD_LIBRARY_PATH
  fi
  
@@ -93,7 +121,7 @@
  # First, figure out the right values for SAGE_NUM_THREADS (default
 --- src/sage/env.py.orig       2017-12-07 19:51:25.554281539 +0000
 +++ src/sage/env.py    2017-12-07 19:51:42.787654650 +0000
-@@ -117,8 +117,8 @@
+@@ -117,13 +117,13 @@
  _add_variable_or_fallback('LOCAL_IDENTIFIER','$HOSTNAME.%s'%os.getpid())
  
  # bunch of sage directories and files
