fix check_dir function so that it allows parsepkgbuild to function normally
git-svn-id: file:///srv/repos/svn-community/svn@861364 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/tensorflow/trunk/PKGBUILD b/tensorflow/trunk/PKGBUILD
--- a/tensorflow/trunk/PKGBUILD
+++ b/tensorflow/trunk/PKGBUILD
@@ -7,7 +7,7 @@ pkgbase=tensorflow
 pkgname=(tensorflow tensorflow-opt tensorflow-cuda tensorflow-opt-cuda python-tensorflow python-tensorflow-opt python-tensorflow-cuda python-tensorflow-opt-cuda)
 pkgver=2.4.1
 _pkgver=2.4.1
-pkgrel=3
+pkgrel=4
 pkgdesc="Library for computation using data flow graphs for scalable machine learning"
 url="https://www.tensorflow.org/"
 license=('APACHE')
@@ -33,6 +33,18 @@ get_pyver () {
 }
 
 check_dir() {
+  # first make sure we do not break parsepkgbuild
+  if ! command -v cp &> /dev/null; then
+    >&2 echo "'cp' command not found. PKGBUILD is probably being checked by parsepkgbuild."
+    if ! command -v install &> /dev/null; then
+      >&2 echo "'install' command also not found. PKGBUILD must be getting checked by parsepkgbuild."
+      >&2 echo "Cannot check if directory '${1}' exists. Ignoring."
+      >&2 echo "If you are not running nacmap or parsepkgbuild, please make sure the PATH is correct and try again."
+      >&2 echo "PATH should not be '/dummy': PATH=$PATH"
+      return 0
+    fi
+  fi
+  # if we are running normally, check the given path
   if [ -d "${1}" ]; then
     return 0
   else
