Todo List: Removed makepkg subroutine
git-svn-id: file:///srv/repos/svn-community/svn@730866 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/trunk/PKGBUILD b/trunk/PKGBUILD
--- a/trunk/PKGBUILD
+++ b/trunk/PKGBUILD
@@ -46,7 +46,7 @@ check() {
     export PYTHONPATH="$PYTHONPATH:/usr/lib/python3.6/site-packages"
     python setup.py install
     python -m gevent.tests
-  ) || warning "Tests failed"
+  ) || echo "Tests failed"
 
   (
     cd "$srcdir"/gevent-$pkgver-py2
@@ -55,7 +55,7 @@ check() {
     export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/site-packages"
     python setup.py install
     python2 -m gevent.tests
-  ) || warning "Tests failed"
+  ) || echo "Tests failed"
 }
 
 package_python-gevent() {
