archrelease: copy trunk to community-x86_64
git-svn-id: file:///srv/repos/svn-community/svn@451125 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/elasticsearch/repos/community-x86_64/elasticsearch-env b/elasticsearch/repos/community-x86_64/elasticsearch-env
--- a/elasticsearch/repos/community-x86_64/elasticsearch-env
+++ b/elasticsearch/repos/community-x86_64/elasticsearch-env
@@ -2,22 +2,26 @@
 
 set -e -o pipefail
 
+JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/default-runtime}
 ES_HOME=/usr/share/elasticsearch
 
 # now set the classpath
 ES_CLASSPATH="$ES_HOME/lib/*"
 
 # now set the path to java
-if [ -x "$JAVA_HOME/bin/java" ]; then
+if [ ! -z "$JAVA_HOME" ]; then
   JAVA="$JAVA_HOME/bin/java"
 else
-  set +e
-  JAVA=`which java`
-  set -e
+  if [ "$(uname -s)" = "Darwin" ]; then
+    # OSX has a different structure
+    JAVA="$ES_HOME/jdk/Contents/Home/bin/java"
+  else
+    JAVA="$ES_HOME/jdk/bin/java"
+  fi
 fi
 
 if [ ! -x "$JAVA" ]; then
-  echo "could not find java; set JAVA_HOME or ensure java is in PATH"
+  echo "could not find java in JAVA_HOME or bundled at $JAVA" >&2
   exit 1
 fi
 
@@ -39,12 +43,19 @@ fi
 
 export HOSTNAME=$HOSTNAME
 
-if [ -z "$ES_PATH_CONF" ]; then ES_PATH_CONF=/etc/elasticsearch; fi
-
 if [ -z "$ES_PATH_CONF" ]; then
-  echo "ES_PATH_CONF must be set to the configuration path"
-  exit 1
+  ES_PATH_CONF=/etc/elasticsearch
 fi
+
+# now make ES_PATH_CONF absolute
+ES_PATH_CONF=`cd "$ES_PATH_CONF"; pwd`
 
 ES_DISTRIBUTION_FLAVOR=default
 ES_DISTRIBUTION_TYPE=tar
+ES_BUNDLED_JDK=false
+
+if [ -z "$ES_TMPDIR" ]; then
+  ES_TMPDIR=`"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.TempDirectory`
+fi
+
+cd "$ES_HOME"
