archrelease: copy trunk to community-i686, community-x86_64
git-svn-id: file:///srv/repos/svn-community/svn@68082 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/open-vm-tools/repos/community-i686/scripts-network.patch b/open-vm-tools/repos/community-i686/scripts-network.patch
--- a/open-vm-tools/repos/community-i686/scripts-network.patch
+++ b/open-vm-tools/repos/community-i686/scripts-network.patch
@@ -1,5 +1,5 @@
---- network.org	2010-04-28 10:21:14.000000000 +0000
-+++ network	2010-04-28 10:24:00.000000000 +0000
+--- network.org	2012-03-17 22:20:11.000000000 +0400
++++ network	2012-03-17 22:18:47.000000000 +0400
 @@ -34,51 +34,6 @@
  
  
@@ -17,47 +17,57 @@
 -#
 -
 -find_networking_script() {
--    local script="error"
--    for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
--        if [ -d "$dir/rc0.d" ] &&
--	    [ -d "$dir/rc1.d" ] &&
--	    [ -d "$dir/rc2.d" ] &&
--	    [ -d "$dir/rc3.d" ] &&
--	    [ -d "$dir/rc4.d" ] &&
--	    [ -d "$dir/rc5.d" ] &&
--	    [ -d "$dir/rc6.d" ]; then
+-   local script="error"
+-   for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
+-      if [ -d "$dir/rc0.d" ] &&
+-         [ -d "$dir/rc1.d" ] &&
+-         [ -d "$dir/rc2.d" ] &&
+-         [ -d "$dir/rc3.d" ] &&
+-         [ -d "$dir/rc4.d" ] &&
+-         [ -d "$dir/rc5.d" ] &&
+-         [ -d "$dir/rc6.d" ]; then
 -
--	    # Now find the appropriate networking script.
--	    if [ -d "$dir/init.d" ]; then
--		if [ -x "$dir/init.d/network" ]; then
--		    script="$dir/init.d/network"
--		elif [ -x "$dir/init.d/networking" ]; then
--		    script="$dir/init.d/networking"
--		fi
--	    else
--		if [ -x "$dir/network" ]; then
--		    script="$dir/network"
--		elif [ -x "$dir/networking" ]; then
--		    script="$dir/networking"
--		fi
--	    fi
--        fi
--    done
+-         # Now find the appropriate networking script.
+-         if [ -d "$dir/init.d" ]; then
+-            if [ -x "$dir/init.d/network" ]; then
+-               script="$dir/init.d/network"
+-            elif [ -x "$dir/init.d/networking" ]; then
+-               script="$dir/init.d/networking"
+-            fi
+-         else
+-            if [ -x "$dir/network" ]; then
+-               script="$dir/network"
+-            elif [ -x "$dir/networking" ]; then
+-               script="$dir/networking"
+-            fi
+-         fi
+-      fi
+-   done
 -
--    echo "$script"
+-   echo "$script"
 -}
 -
 -
 -#
- # save_active_NIC_list --
+ # run_network_script --
  #
- #    Records a list of every active NIC to /var/run/vmware-active-nics.
-@@ -205,7 +160,7 @@
-    exitCode=0
-    activeList=/var/run/vmware-active-nics
+ # Finds out how to run the system's script used to control networking, and
+@@ -87,17 +42,7 @@
+ #
+ run_network_script()
+ {
+-   script=`find_networking_script`
+-   [ "$script" != "error" ] || Panic "Cannot find system networking script."
+-
+-   # Using SysV "service" if it exists, otherwise fall back to run the script directly
+-   service=`which service 2>/dev/null`
+-   if [ $? = 0 -a -n "$service" ]; then
+-      serviceName=`basename "$script"`
+-      "$service" "$serviceName" "$1"
+-   else
+-      "$script" "$1"
+-   fi
++  /etc/rc.d/network "$1"
+ }
  
--   networkScript=`find_networking_script`
-+   networkScript=/etc/rc.d/network
-    [ "$networkScript" != "error" ] || Panic "Cannot find system networking script."
  
-    # XXX Are these really necessary?  If so, we should have seen customer
