upgpkg: python-py 1.4.33-1
git-svn-id: file:///srv/repos/svn-community/svn@216868 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/python-py/trunk/PKGBUILD b/python-py/trunk/PKGBUILD
--- a/python-py/trunk/PKGBUILD
+++ b/python-py/trunk/PKGBUILD
@@ -8,43 +8,45 @@
 
 pkgbase=python-py
 pkgname=('python-py' 'python2-py')
-pkgver=1.4.32
-pkgrel=2
+pkgver=1.4.33
+pkgrel=1
 pkgdesc="library with cross-python path, ini-parsing, io, code, log facilities"
 arch=('any')
 license=('MIT')
 url="http://py.readthedocs.io/"
-makedepends=('python-setuptools' 'python2-setuptools' 'git')
-checkdepends=('python-pytest' 'python2-pytest')
-source=("git+https://github.com/pytest-dev/py.git#tag=$pkgver")
-sha512sums=('SKIP')
+makedepends=('python-setuptools' 'python2-setuptools')
+checkdepends=('python-pytest-runner' 'python2-pytest-runner')
+source=("$pkgbase-$pkgver.tar.gz::https://github.com/pytest-dev/py/archive/$pkgver.tar.gz")
+sha512sums=('a0d760813b20e8549b0c6d91fb115217c9b661d7e1218813c7a9d4e659eb5a8c027f1de71093b06002da2879640b06deb26444dcf326ca38aec593710d7637ec')
 
 prepare() {
-  cp -a py{,-py2}
+  cp -a py-$pkgver{,-py2}
+
+  export LC_CTYPE=en_US.UTF-8
 }
 
 build() {
-  cd "$srcdir"/py
+  cd "$srcdir"/py-$pkgver
   python setup.py build
 
-  cd "$srcdir"/py-py2
+  cd "$srcdir"/py-$pkgver-py2
   python2 setup.py build
 }
 
 check() {
-  export LC_CTYPE=en_US.UTF-8
+  # Known failure: https://github.com/pytest-dev/py/issues/104
 
-  cd "$srcdir"/py
-  PYTHONPATH="$PWD/build/lib:$PYTHONPATH" py.test
+  cd "$srcdir"/py-$pkgver
+  python setup.py pytest || warning "Tests failed"
 
-  cd "$srcdir"/py-py2
-  PYTHONPATH="$PWD/build/lib:$PYTHONPATH" py.test2
+  cd "$srcdir"/py-$pkgver-py2
+  python2 setup.py pytest || warning "Tests failed"
 }
 
 package_python-py() {
   depends=('python')
 
-  cd py
+  cd py-$pkgver
   python setup.py install --root="$pkgdir" --optimize=1
   install -D -m644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 }
@@ -52,7 +54,7 @@ package_python-py() {
 package_python2-py() {
   depends=('python2')
 
-  cd py-py2
+  cd py-$pkgver-py2
   python2 setup.py install --root="$pkgdir" --optimize=1
   install -D -m644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 }
