2.36.11+70+g00e03a272-1
git-svn-id: file:///srv/repos/svn-community/svn@308978 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/lib32-gdk-pixbuf2/trunk/PKGBUILD b/lib32-gdk-pixbuf2/trunk/PKGBUILD
--- a/lib32-gdk-pixbuf2/trunk/PKGBUILD
+++ b/lib32-gdk-pixbuf2/trunk/PKGBUILD
@@ -2,24 +2,21 @@
 # Maintainer: Felix Yan <felixonmars@archlinux.org>
 # Contributor: Ionut Biru <ibiru@archlinux.org>
 
-_pkgbasename=gdk-pixbuf2
-pkgname=lib32-$_pkgbasename
-pkgver=2.36.6
+pkgname=lib32-gdk-pixbuf2
+pkgver=2.36.11+70+g00e03a272
 pkgrel=1
 pkgdesc="An image loading library (32-bit)"
-arch=('x86_64')
-url="http://www.gtk.org/"
-license=('LGPL2.1')
-depends=(lib32-glib2 lib32-libpng lib32-libtiff lib32-libjpeg lib32-libx11
-         $_pkgbasename)
-makedepends=('gtk-doc' 'gobject-introspection' 'git')
-options=('!docs')
-install=gdk-pixbuf2.install
-_commit=d8ae54bc5e3e31d43acf410a6689be2d40567b03  # tags/2.36.6^0
+arch=(x86_64)
+url="https://wiki.gnome.org/Projects/GdkPixbuf"
+license=(LGPL2.1)
+depends=(lib32-glib2 lib32-libpng lib32-libtiff lib32-libjpeg lib32-libx11 gdk-pixbuf2)
+makedepends=(gtk-doc gobject-introspection git docbook-xsl meson)
+install=lib32-gdk-pixbuf2.install
+_commit=00e03a2727b276ea32e2902dd9b41298ff1f9e96  # master
 source=("git+https://git.gnome.org/browse/gdk-pixbuf#commit=$_commit"
         gdk-pixbuf-query-loaders-32.hook)
 sha256sums=('SKIP'
-            'b9a1e5b0d18a4259b9b87ccb3f055402c89c85f7bddb5ed9d8b407de537f7d86')
+            '3fed95ad7075698313caba78c84b4f7eb9935cc5c8cc99412fc56d8d34ef700f')
 
 pkgver() {
   cd gdk-pixbuf
@@ -28,7 +25,6 @@ pkgver() {
 
 prepare() {
   cd gdk-pixbuf
-  NOCONFIGURE=1 ./autogen.sh
 }
 
 build() {
@@ -37,27 +33,22 @@ build() {
   export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
   export CFLAGS="-I/usr/include/libtiff32 $CFLAGS"
 
-  cd gdk-pixbuf
-  ./configure --prefix=/usr  --libdir=/usr/lib32 \
-    --without-libjasper \
-    --with-x11 \
-    --with-included-loaders=png
-  sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
-  make
+  arch-meson gdk-pixbuf build --libdir=/usr/lib32
+  ninja -C build
+}
+
+check() {
+  cd build
+  # pixbuf-randomly-modified fails randomly
+  meson test -t 3 || :
 }
 
 package() {
-  cd gdk-pixbuf
-  make DESTDIR="$pkgdir" install
-
-  rm -rf "${pkgdir}"/etc
-  rm -rf "${pkgdir}"/usr/{include,share}
-
-  cd "${pkgdir}"/usr/bin
-  mv gdk-pixbuf-query-loaders{,-32}
-  mv gdk-pixbuf-thumbnailer{,-32}
-  rm gdk-pixbuf-pixdata gdk-pixbuf-csource
-  install -Dm644 "${srcdir}/gdk-pixbuf-query-loaders-32.hook" -t "$pkgdir/usr/share/libalpm/hooks"
+  DESTDIR="$pkgdir" ninja -C build install
+  rm -rf "$pkgdir"/usr/{include,lib,share}
+  find "$pkgdir/usr/bin" -type f -not -name gdk-pixbuf-query-loaders -delete
+  mv "$pkgdir"/usr/bin/gdk-pixbuf-query-loaders{,-32}
+  install -Dt "$pkgdir/usr/share/libalpm/hooks" -m644 *.hook
 }
 
 # vim:set ts=2 sw=2 et:
