Todo List: Removed makepkg subroutine
git-svn-id: file:///srv/repos/svn-community/svn@730866 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/hdf5-openmpi/trunk/PKGBUILD b/hdf5-openmpi/trunk/PKGBUILD
--- a/hdf5-openmpi/trunk/PKGBUILD
+++ b/hdf5-openmpi/trunk/PKGBUILD
@@ -83,7 +83,7 @@ check() {
     export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/hl/c++/src/.libs/
     export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/hl/fortran/src/.libs/
     # This is a parallel build, they are always OpenMPI bugs
-    make check || warning "Tests failed"
+    make check || echo "Tests failed"
 }
 
 package() {
