8.1.0 update, use rmprofile multilib (the same as official ARM toolchain)
git-svn-id: file:///srv/repos/svn-community/svn@318972 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/arm-none-eabi-gcc/trunk/enable-with-multilib-list-for-arm.patch b/arm-none-eabi-gcc/trunk/enable-with-multilib-list-for-arm.patch
--- a/arm-none-eabi-gcc/trunk/enable-with-multilib-list-for-arm.patch
+++ b/arm-none-eabi-gcc/trunk/enable-with-multilib-list-for-arm.patch
@@ -1,14 +1,14 @@
-commit 71587241301d28b68bbe2f41c5eb2856053c750c
+commit ebea823006d493d3b994c464ae599349cd1cfeaf
 Author: Anatol Pomozov <anatol.pomozov@gmail.com>
-Date:   Tue May 9 21:19:27 2017 -0700
+Date:   Fri May 4 21:15:49 2018 -0700
 
     ARM patch https://gcc.gnu.org/ml/gcc-patches/2012-05/msg00083/enable-with-multilib-list-for-arm.patch
 
 diff --git a/gcc/Makefile.in b/gcc/Makefile.in
-index f675e073ecc..cced5329b47 100644
+index 20bee0494..26898699d 100644
 --- a/gcc/Makefile.in
 +++ b/gcc/Makefile.in
-@@ -558,6 +558,7 @@ lang_opt_files=@lang_opt_files@ $(srcdir)/c-family/c.opt $(srcdir)/common.opt
+@@ -567,6 +567,7 @@ lang_opt_files=@lang_opt_files@ $(srcdir)/c-family/c.opt $(srcdir)/common.opt
  lang_specs_files=@lang_specs_files@
  lang_tree_files=@lang_tree_files@
  target_cpu_default=@target_cpu_default@
@@ -17,10 +17,10 @@ index f675e073ecc..cced5329b47 100644
  extra_modes_file=@extra_modes_file@
  extra_opt_files=@extra_opt_files@
 diff --git a/gcc/config.gcc b/gcc/config.gcc
-index b8bb4d65825..713e35b62af 100644
+index a5defb0f0..f8f964757 100644
 --- a/gcc/config.gcc
 +++ b/gcc/config.gcc
-@@ -1140,7 +1140,7 @@ arm*-*-eabi* | arm*-*-symbianelf* | arm*-*-rtems* | arm*-*-fuchsia*)
+@@ -1181,7 +1181,7 @@ arm*-*-eabi* | arm*-*-symbianelf* | arm*-*-rtems* | arm*-*-fuchsia*)
  	case ${target} in
  	arm*-*-eabi*)
  	  tm_file="$tm_file newlib-stdint.h"
@@ -29,42 +29,26 @@ index b8bb4d65825..713e35b62af 100644
  	  use_gcc_stdint=wrap
  	  ;;
  	arm*-*-fuchsia*)
-@@ -3787,56 +3787,6 @@ case "${target}" in
- 			echo "Switch \"--with-tune\" may not be used with switch \"--with-cpu\""  1>&2
+@@ -3897,43 +3897,6 @@ case "${target}" in
  			exit 1
  		fi
--
+ 
 -		# Add extra multilibs
 -		if test "x$with_multilib_list" != x; then
 -			arm_multilibs=`echo $with_multilib_list | sed -e 's/,/ /g'`
--			case ${arm_multilibs} in
--			aprofile)
--				# Note that arm/t-aprofile is a
--				# stand-alone make file fragment to be
--				# used only with itself.  We do not
--				# specifically use the
--				# TM_MULTILIB_OPTION framework because
--				# this shorthand is more
--				# pragmatic.
--				tmake_profile_file="arm/t-aprofile"
--				;;
--			rmprofile)
--				# Note that arm/t-rmprofile is a
--				# stand-alone make file fragment to be
--				# used only with itself.  We do not
--				# specifically use the
--				# TM_MULTILIB_OPTION framework because
--				# this shorthand is more
--				# pragmatic.
--				tmake_profile_file="arm/t-rmprofile"
--				;;
--			default)
--				;;
--			*)
--				echo "Error: --with-multilib-list=${with_multilib_list} not supported." 1>&2
--				exit 1
--				;;
--			esac
+-			if test "x${arm_multilibs}" != xdefault ; then
+-				for arm_multilib in ${arm_multilibs}; do
+-					case ${arm_multilib} in
+-					aprofile|rmprofile)
+-						tmake_profile_file="arm/t-multilib"
+-						;;
+-					*)
+-						echo "Error: --with-multilib-list=${with_multilib_list} not supported." 1>&2
+-						exit 1
+-						;;
+-					esac
+-				done
+-			fi
 -
 -			if test "x${tmake_profile_file}" != x ; then
 -				# arm/t-aprofile and arm/t-rmprofile are only
@@ -79,16 +63,19 @@ index b8bb4d65825..713e35b62af 100644
 -				    echo "Error: You cannot use any of --with-arch/cpu/fpu/float/mode with --with-multilib-list=${with_multilib_list}" 1>&2
 -				    exit 1
 -				fi
--
+-				# But pass the default value for float-abi
+-				# through to the multilib selector
+-				with_float="soft"
 -				tmake_file="${tmake_file} ${tmake_profile_file}"
+-				TM_MULTILIB_CONFIG="$with_multilib_list"
 -			fi
 -		fi
+ 		target_cpu_cname=${target_cpu_cname:-arm6}
+ 		with_cpu=${with_cpu:-$target_cpu_cname}
  		;;
- 
- 	fr*-*-*linux*)
 diff --git a/gcc/config/arm/t-mlibs b/gcc/config/arm/t-mlibs
 new file mode 100644
-index 00000000000..5720cf7503d
+index 000000000..5720cf750
 --- /dev/null
 +++ b/gcc/config/arm/t-mlibs
 @@ -0,0 +1,89 @@
@@ -182,10 +169,10 @@ index 00000000000..5720cf7503d
 +MULTILIB_REUSE      += mthumb/march.armv7/mfloat-abi.hard/mfpu.vfpv3-d16=marm/march.armv7/mfloat-abi.hard/mfpu.vfpv3-d16
 +endif
 diff --git a/gcc/configure b/gcc/configure
-index ea73b151a4e..c609f25e50c 100755
+index e5a5783f7..1383d30dd 100755
 --- a/gcc/configure
 +++ b/gcc/configure
-@@ -772,6 +772,7 @@ SET_MAKE
+@@ -775,6 +775,7 @@ SET_MAKE
  accel_dir_suffix
  real_target_noncanonical
  enable_as_accelerator
@@ -193,16 +180,8 @@ index ea73b151a4e..c609f25e50c 100755
  REPORT_BUGS_TEXI
  REPORT_BUGS_TO
  PKGVERSION
-@@ -7763,6 +7764,7 @@ else
- fi
- 
- 
-+
- # -------------------------
- # Checks for other programs
- # -------------------------
 diff --git a/gcc/configure.ac b/gcc/configure.ac
-index 9d4c792a33f..abd988eb113 100644
+index b066cc609..95f5d025d 100644
 --- a/gcc/configure.ac
 +++ b/gcc/configure.ac
 @@ -1007,6 +1007,7 @@ AC_ARG_WITH(multilib-list,
