Julia 1.0 currently does not build here
git-svn-id: file:///srv/repos/svn-community/svn@371229 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/julia/trunk/PKGBUILD b/julia/trunk/PKGBUILD
--- a/julia/trunk/PKGBUILD
+++ b/julia/trunk/PKGBUILD
@@ -8,40 +8,28 @@
 pkgbase=julia
 pkgname=(julia julia-docs)
 epoch=2
-pkgver=0.6.4
+pkgver=1.0.0
 pkgrel=1
 arch=('x86_64')
 pkgdesc='High-level, high-performance, dynamic programming language'
 url='https://julialang.org/'
 license=('MIT')
 depends=('fftw' 'hicolor-icon-theme' 'libgit2' 'libunwind' 'libutf8proc>=2' 'mpfr' 'pcre2' 'suitesparse')
-makedepends=('chrpath' 'cmake' 'gcc-fortran' 'gmp' 'gtk-update-icon-cache' 'python2')
+makedepends=('chrpath' 'cmake' 'gcc-fortran' 'gmp' 'gtk-update-icon-cache' 'patchelf' 'python2')
 options=('!emptydirs' 'staticlibs')
-source=("https://github.com/JuliaLang/$pkgbase/releases/download/v$pkgver/$pkgbase-$pkgver-full.tar.gz"{,.asc}
-        'julia-libunwind-version.patch'
-        'julia-makefile.patch')
-sha256sums=('2b2f5543ad4206eb40c7b850cdfc5a812c6df0b2b5bcf6a3206c0e446d988f1b'
-            'SKIP'
-            '16009ce454f58463464027cbaf6186ccfab84c37660a52fb1ec3a0f514df64f9'
-            '342b43532fbace3508688eee879113160e01cbbda29610b53f2f34796bc0312a')
+source=("https://github.com/JuliaLang/$pkgbase/releases/download/v$pkgver/$pkgbase-$pkgver-full.tar.gz"{,.asc})
+sha256sums=('1a2497977b1d43bb821a5b7475b4054b29938baae8170881c6b8dd4099d133f1' 'SKIP')
 validpgpkeys=('3673DF529D9049477F76B37566E3C7DC03D6E495') # Julia (Binary signing key) <buildbot@julialang.org>
 
-prepare() {
-  cd "$pkgbase"
-  patch -p1 -i ../julia-libunwind-version.patch
-  patch -p0 -i ../julia-makefile.patch # make 'make install' really just install
-}
-
 build() {
-  #
-  # See FS#57387 for why USE_SYSTEM_LLVM=0 is used, for now
-  # See FS#58221 for why USE_SYSTEM_ARPACK=0 is used, for now
-  #
-  # patchelf is not even used unless $(private_libdir_rel) != $(build_private_libdir_rel)
-  # but we USE_SYSTEM_PATCHELF=1 to prevent building it. This is why it is not in makedepends.
-  #
   export CFLAGS="$CFLAGS -w"
   export CXXFLAGS="$CXXFLAGS -w"
+  #
+  # USE_SYSTEM_LIBUNWIND=1 fails
+  # USE_SYSTEM_LIBM=1 fails
+  # USE_SYSTEM_LLVM=1 fails (see FS#57387)
+  # USE_SYSTEM_ARPACK=1 fails (see FS#58221)
+  #
   make -C "$pkgbase" \
     prefix=/usr \
     sysconfdir=/etc \
@@ -57,8 +45,8 @@ build() {
     USE_SYSTEM_GMP=1 \
     USE_SYSTEM_LAPACK=0 \
     USE_SYSTEM_LIBGIT2=1 \
-    USE_SYSTEM_LIBM=1 \
-    USE_SYSTEM_LIBUNWIND=1 \
+    USE_SYSTEM_LIBM=0 \
+    USE_SYSTEM_LIBUNWIND=0 \
     USE_SYSTEM_LIBUV=0 \
     USE_SYSTEM_LLVM=0 \
     USE_SYSTEM_MPFR=1 \
@@ -91,8 +79,8 @@ package_julia() {
     USE_SYSTEM_GMP=1 \
     USE_SYSTEM_LAPACK=0 \
     USE_SYSTEM_LIBGIT2=1 \
-    USE_SYSTEM_LIBM=1 \
-    USE_SYSTEM_LIBUNWIND=1 \
+    USE_SYSTEM_LIBM=0 \
+    USE_SYSTEM_LIBUNWIND=0 \
     USE_SYSTEM_LIBUV=0 \
     USE_SYSTEM_LLVM=0 \
     USE_SYSTEM_MPFR=1 \
@@ -102,7 +90,7 @@ package_julia() {
     USE_SYSTEM_PCRE=1 \
     USE_SYSTEM_SUITESPARSE=1 \
     USE_SYSTEM_UTF8PROC=1 \
-    install
+    install || true
 
   # Remove duplicate man-page from julia/doc
   rm -rf "$pkgdir/usr/share/julia/doc/man"
