upgpkg: gcc-multilib 4.5.1-8 Update to core/gcc 4.5.1-2
git-svn-id: file:///srv/repos/svn-community/svn@33690 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/gcc-multilib/trunk/PKGBUILD b/gcc-multilib/trunk/PKGBUILD
--- a/gcc-multilib/trunk/PKGBUILD
+++ b/gcc-multilib/trunk/PKGBUILD
@@ -8,28 +8,29 @@
 pkgbase='gcc-multilib'
 pkgname=('gcc-multilib' 'gcc-libs-multilib' 'lib32-gcc-libs' 'gcc-fortran-multilib' 'gcc-objc-multilib' 'gcc-ada-multilib')
 pkgver=4.5.1
-pkgrel=7
-_corerel=1 # core/gcc pkgrel this is based on
-#_snapshot=4.5-20100610
-_libstdcppmanver=20100719	# Note: check source directory name when updating this
+pkgrel=8
+_corerel=2 # core/gcc pkgrel this is based on
+_snapshot=4.5-20101125
+_libstdcppmanver=4.5.2		# Note: check source directory name when updating this
 pkgdesc="The GNU Compiler Collection for multilib"
 arch=('x86_64')
 license=('GPL' 'LGPL' 'custom')
 url="http://gcc.gnu.org"
-makedepends=('binutils-multilib>=2.20.1' 'libmpc>=0.8.2-2' 'cloog-ppl>=0.15.9-2' 'elfutils' 'gcc-ada-multilib'
+makedepends=('binutils-multilib>=2.20.1' 'libmpc>=0.8.2-2' 'cloog-ppl>=0.15.9-2' 'elfutils' 'gcc-ada-multilib' 'dejagnu'
              'glibc>=2.11.1-2' 'lib32-glibc>=2.12.1')
 options=('!libtool' '!emptydirs')
-source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{core,g++,fortran,objc,ada}-${pkgver}.tar.bz2
-	#ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{core,g++,fortran,objc,ada}-${_snapshot}.tar.bz2
-	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api.${_libstdcppmanver}.man.tar.bz2
+source=(#ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{core,g++,fortran,objc,ada,testsuite}-${pkgver}.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{core,g++,fortran,objc,ada,testsuite}-${_snapshot}.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api-${_libstdcppmanver}.man.tar.bz2
 	gcc_pure64.patch
 	gcc-hash-style-both.patch)
-md5sums=('dc8959e31b01a65ce10d269614815054'
-         'b294953ff0bb2f20c7acb2bf005d832a'
-         '7567c2f8df8a8bf61b48fe414b88de65'
-         '3c11b7037896e967eddf8178af2ddd98'
-         'c92111e2e22fc60d1e0adb1b5c7fa4f9'
-         '226ae0c6364cfe2c1f7ac88d06088d5a'
+md5sums=('7023dd06e5db9141c590f0c1cfb742f5'
+         '1e793092ca05638421c21e8ad6a5a10f'
+         'd0b75cd4144b744a7abeca36d19b9726'
+         '9f4ef57841ab819563003ae65a8281e3'
+         'cada64872a8414e38ab2e4684644cec6'
+         'aba643dac79c35eb7f69a027c8dc0ed7'
+         '2776eab5ebb7f9cc62dd2199a3a24382'
          '22cec272f9cc2801d3cd348feaca888b'
          '6fd395bacbd7b6e47c7b74854b478363')
 
@@ -64,11 +65,10 @@ build() {
 
   echo ${pkgver} > gcc/BASE-VER
 
-  # Add PATH for pod2man. Needed for manpages
-  export PATH="$PATH:/usr/lib/perl5/core_perl/bin"
-
-  mkdir build && cd build      
-  ../configure --prefix=/usr --enable-languages=c,c++,fortran,objc,obj-c++,ada \
+  cd ${srcdir}
+  mkdir gcc-build && cd gcc-build
+  ${_basedir}/configure --prefix=/usr \
+      --enable-languages=c,c++,fortran,objc,obj-c++,ada \
       --enable-shared --enable-threads=posix --enable-__cxa_atexit \
       --enable-clocale=gnu --enable-gnu-unique-object \
       --enable-lto --enable-plugin \
@@ -77,6 +77,14 @@ build() {
       --libdir=/usr/lib --libexecdir=/usr/lib \
       --mandir=/usr/share/man --infodir=/usr/share/info
   make
+
+  # increase stack size to prevent test failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
+  ulimit -s 32768
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  ${_basedir}/contrib/test_summary
 }
 
 package_gcc-libs-multilib()
@@ -87,7 +95,7 @@ package_gcc-libs-multilib()
   conflicts=('gcc-libs')
   install=gcc-libs.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
   for lib in libmudflap libgomp libssp libstdc++-v3/src; do
     make -j1 -C $CHOST/$lib DESTDIR=${pkgdir} install-toolexeclibLTLIBRARIES
@@ -98,7 +106,6 @@ package_gcc-libs-multilib()
   make -j1 DESTDIR=${pkgdir} install-target-libgfortran
 
   make -j1 DESTDIR=${pkgdir} install-target-libobjc
-
   # I thought I said to only install the lib...
   rm -rf ${pkgdir}/usr/lib/gcc/
   rm -rf ${pkgdir}/usr/lib32
@@ -116,7 +123,7 @@ package_lib32-gcc-libs()
   pkgdesc="Runtime libraries shipped by GCC for C and C++ languages (32-bit)"
   depends=('lib32-glibc>=2.12.1' "gcc-libs>=$pkgver-$_corerel")
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C $CHOST/32/libgcc DESTDIR=${pkgdir} install-shared
   for lib in libmudflap libgomp libssp libstdc++-v3/src; do
     make -j1 -C $CHOST/32/$lib DESTDIR=${pkgdir} install-toolexeclibLTLIBRARIES
@@ -145,7 +152,7 @@ package_gcc-multilib()
   conflicts=('gcc')
   install=gcc.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   
   # much, much easier to install the lot and clean-up the mess
   make -j1 DESTDIR=${pkgdir} install
@@ -196,8 +203,6 @@ EOF
   install -dm755 ${pkgdir}/usr/share/man/man3
   install -m644 ${srcdir}/libstdc++-api-${_libstdcppmanver}.man/man3/* \
     ${pkgdir}/usr/share/man/man3/
-  # deal with conflicts...
-  rm -f ${pkgdir}/usr/share/man/man3/{ctime,queue,random,regex,string}.3
 
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
@@ -212,7 +217,7 @@ package_gcc-fortran-multilib()
   conflicts=('gcc-fortran')
   install=gcc-fortran.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 DESTDIR=$pkgdir install-target-libgfortran
   make -j1 -C $CHOST/libgomp DESTDIR=$pkgdir install-nodist_fincludeHEADERS
   make -j1 -C gcc DESTDIR=$pkgdir fortran.install-{common,man,info}
@@ -233,7 +238,7 @@ package_gcc-objc-multilib()
   provides=("gcc-objc=$pkgver-$_corerel")
   conflicts=('gcc-objc')
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 DESTDIR=$pkgdir install-target-libobjc
   install -dm755 $pkgdir/usr/lib/gcc/$CHOST/$pkgver/
   install -m755 gcc/cc1obj{,plus} $pkgdir/usr/lib/gcc/$CHOST/$pkgver/
@@ -254,7 +259,7 @@ package_gcc-ada-multilib()
   conflicts=('gcc-ada')
   install=gcc-ada.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C gcc DESTDIR=$pkgdir ada.install-{common,info}
   install -m755 gcc/gnat1 $pkgdir/usr/lib/gcc/$CHOST/$pkgver
   make -j1 -C $CHOST/32/libada DESTDIR=${pkgdir} install-gnatlib
