2.20
git-svn-id: file:///srv/repos/svn-community/svn@118722 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/lib32-glibc/trunk/PKGBUILD b/lib32-glibc/trunk/PKGBUILD
--- a/lib32-glibc/trunk/PKGBUILD
+++ b/lib32-glibc/trunk/PKGBUILD
@@ -4,45 +4,31 @@
 # Contributor: Allan McRae <allan@archlinux.org>
 
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
-# NOTE: valgrind requires rebuilt with each major glibc version
 
 _pkgbasename=glibc
 pkgname=lib32-$_pkgbasename
-pkgver=2.19
-pkgrel=5
+pkgver=2.20
+pkgrel=1
 pkgdesc="GNU C Library (32-bit)"
 arch=('x86_64')
 url="http://www.gnu.org/software/libc"
 license=('GPL' 'LGPL')
 groups=()
 depends=()
-makedepends=('gcc-multilib>=4.8')
+makedepends=('gcc-multilib>=4.9')
 backup=()
-options=('!strip' '!emptydirs' 'staticlibs')
+
+
+options=('!strip' 'staticlibs' '!emptydirs')
+install=
 source=(http://ftp.gnu.org/gnu/libc/${_pkgbasename}-${pkgver}.tar.xz{,.sig}
-        glibc-2.19-xattr_header.patch
-        glibc-2.19-fix-sign-in-bsloww1-input.patch
-        glibc-2.19-tzselect-default.patch
         lib32-glibc.conf)
-md5sums=('e26b8cc666b162f999404b03970f14e4'
+md5sums=('948a6e06419a01bd51e97206861595b0'
          'SKIP'
-         '39a4876837789e07746f1d84cd8cb46a'
-         '755a1a9d7844a5e338eddaa9a5d974cd'
-         'c772dc99ddd8032ecbf43884ae0cf42e'
          '6e052f1cb693d5d3203f50f9d4e8c33b')
+validpgpkeys=('F37CDAB708E65EA183FD1AF625EF0A436C2A4AFF')
 
 prepare() {
-  cd ${srcdir}/${_pkgbasename}-${pkgver}
-
-  # fix for {linux,sys}/xattr.h incompatibility - commit fdbe8eae
-  patch -p1 -i $srcdir/glibc-2.19-xattr_header.patch
-
-  # fix issues in sin/cos slow path calculation - commit ffe768a9
-  patch -p1 -i $srcdir/glibc-2.19-fix-sign-in-bsloww1-input.patch
-
-  # fix tzselect with missing TZDIR - commit 893b4f37/c72399fb
-  patch -p1 -i $srcdir/glibc-2.19-tzselect-default.patch
-
   mkdir ${srcdir}/glibc-build
 }
 
@@ -56,6 +42,7 @@ build() {
   #fi
 
   echo "slibdir=/usr/lib32" >> configparms
+  echo "rtlddir=/usr/lib32" >> configparms
   echo "sbindir=/usr/bin" >> configparms
   echo "rootsbindir=/usr/bin" >> configparms
 
@@ -70,7 +57,7 @@ build() {
       --libdir=/usr/lib32 --libexecdir=/usr/lib32 \
       --with-headers=/usr/include \
       --with-bugurl=https://bugs.archlinux.org/ \
-      --enable-add-ons=nptl,libidn \
+      --enable-add-ons \
       --enable-obsolete-rpc \
       --enable-kernel=2.6.32 \
       --enable-bind-now --disable-profile \
@@ -89,7 +76,7 @@ build() {
   make
 
   # remove harding in preparation to run test-suite
-  sed -i '4,6d' configparms
+  sed -i '5,7d' configparms
 }
 
 check() {
@@ -98,9 +85,8 @@ check() {
 
   cd ${srcdir}/glibc-build
 
-  # ULP failures on i686 are all small and can be ignored
-  # tst-cleanupx4.out failure on i686 needs investigating...
-  make -k check || true
+  # tst-cleanupx4 failure on i686 is "expected"
+  make check || true
 }
 
 package() {
