archrelease: copy trunk to community-x86_64
git-svn-id: file:///srv/repos/svn-community/svn@606405 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/repos/community-x86_64/PKGBUILD b/repos/community-x86_64/PKGBUILD
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer: Jerome Leclanche <jerome@leclan.ch>
 
 pkgname=pgadmin4
-pkgver=4.18
+pkgver=4.19
 pkgrel=1
 pkgdesc='Comprehensive design and management interface for PostgreSQL'
 url='https://www.pgadmin.org/'
@@ -17,7 +17,7 @@ depends=('qt5-base' 'postgresql-libs' 'hicolor-icon-theme' 'python'
          'python-cryptography' 'python-sqlalchemy' 'python-testtools'
          'python-webencodings' 'python-werkzeug' 'python-dateutil'
          'python-flask-gravatar' 'python-flask-mail' 'python-flask-principal'
-         'python-flask-paranoid' 'python-sshtunnel' 'python-flask-security'
+         'python-flask-paranoid' 'python-sshtunnel' 'python-flask-security-too'
          'python-werkzeug' 'python-flask-compress')
 makedepends=('python-setuptools' 'python-sphinx' 'python-extras' 'python-fixtures'
              'python-html5lib' 'python-pbr' 'python-mimeparse' 'python-pyrsistent'
@@ -29,12 +29,12 @@ source=(https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v${pkgver}/source/${pkgn
         python-3.8.patch
         pgadmin4-python-de-vendor-venv-paths.patch)
 validpgpkeys=('E8697E2EEF76C02D3A6332778881B2A8210976F2') # Package Manager (Package Signing Key) <packages@pgadmin.org>
-sha512sums=('9c649c493cc6278672509603f2bd43f44a14dd431ee0ac571d75a63553ebb005f0cdf954659ced3bdc408e51377fe46c58a0aca6a0181d9b5ef94af55969c3d9'
+sha512sums=('d77afdd031649675240b46a8024d5869290c5600a66f543993472bf10ee3f87d5a4d59b69e722b43593a6f9537dc0b176f3771efe66d25bfd8c83443c4905711'
             'SKIP'
             'b19dda3331585010c759099eb09f4db288ce4cd3d36882b56748e1e3756dc7bee2899d7438d496280498ec6a60f6e1ba90309d49fc599403f1fdc7e8817b6645'
             '16d00dc2095904a6b12da7039458f632873829ad98d4d7653eac5804032ba92097ccae4488d56467d0ea9bd64e2654a3dead73eb7924c947ff1737ff6e3b4745'
             'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e'
-            'a1647d80dfbae6e1ef7cc6d59cd763e3b1e8c3208a7b4d6cac6ae9afe364359c3f675d6b368bf5a0fd845a2cbc11ec5a62e4236a674dce82a461c0fb9685e789'
+            '9961c8e109baa25c1bd0a1a86262e5736a448e7fb19b0be992a29d95b2cba05d9427c063cd840b85262bacd93d9c65ccd40e3808166c7654972be203cbc72c03'
             '70c8e589421ab50cf81753fbcfb5df65669b0feeefa3a57ee574b3785424fd107af720fc7007e52876798a46fae88f2c02dbf156aa096397afa0f85ac04fdb76')
 
 prepare() {
@@ -74,12 +74,18 @@ prepare() {
     -e '/Flask-Principal>?=/d' \
     -e '/Flask-Paranoid>?=/d' \
     -e '/htmlmin>?=/d' \
-    -e '/Flask-Security>?=/d' \
+    -e '/Flask-Security-Too>?=/d' \
     -e '/Flask-HTMLmin>?=/d' \
     -e '/Flask-Compress>?=/d' \
     -e '/sshtunnel>?=/d' \
-    -e '/Werkzeug>?=/d'
-  cat requirements.txt
+    -e '/Werkzeug>?=/d' \
+    -e '/^#.*/d' \
+    -e '/^$/d'
+  if [[ -s requirements.txt ]]; then
+    echo "ERROR: requirements.txt must be empty:"
+    cat requirements.txt
+    exit 1
+  fi
 }
 
 build() {
@@ -91,6 +97,8 @@ build() {
   make docs
 
   cd runtime
+  export CFLAGS+=" ${CPPFLAGS}"
+  export CXXFLAGS+=" ${CPPFLAGS}"
   qmake CONFIG+=release
   make
 }
