archrelease: copy trunk to community-x86_64
git-svn-id: file:///srv/repos/svn-community/svn@1045131 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/repos/community-x86_64/PKGBUILD b/repos/community-x86_64/PKGBUILD
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -13,8 +13,9 @@ pkgname=(
  dotnet-targeting-pack
  aspnet-targeting-pack
 )
-pkgver=5.0.8.sdk205
+pkgver=6.0.0.sdk100
 pkgrel=1
+_bootstrapver=0.1.0-6.0.100-bootstrap.29
 arch=(x86_64)
 url=https://www.microsoft.com/net/core
 license=(MIT)
@@ -22,8 +23,6 @@ makedepends=(
   bash
   clang
   cmake
-  dotnet-runtime-3.1
-  dotnet-sdk
   git
   icu
   inetutils
@@ -33,7 +32,7 @@ makedepends=(
   libxml2
   lldb
   llvm
-  lttng-ust
+  lttng-ust2.12
   nodejs
   openssl
   systemd
@@ -41,60 +40,67 @@ makedepends=(
 )
 optdepends=('bash-completion: Bash completion support')
 options=(staticlibs)
-_tag=42ac4d6d5a1d36cc92c89d0e810fdd2f5ed109c6
+_tag=9e8b04bbff820c93c142f99a507a46b976f5c14c
 source=(
-  dotnet-source-build::git+https://github.com/dotnet/source-build.git#tag=${_tag}
+  dotnet-installer::git+https://github.com/dotnet/installer.git#tag=${_tag}
+  https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.${_bootstrapver}.tar.gz
   dotnet.sh
-  9999-runtime-link-order.patch
-  9999-sdk-telemetry-optout.patch
+  dotnet-core-runtime-disable-package-validation.patch
+  dotnet-core-sdk-telemetry-optout.patch
 )
+noextract=(Private.SourceBuilt.Artifacts.${_bootstrapver}.tar.gz)
 b2sums=('SKIP'
+        'a0171c3a8acdb3f5c56359e274984081f5e2c54bd02df677987dc57711e856ccde9266a739bc7db4b17da3ff7f922a3370a23d2be2e5d92e9ebf17c016c2e6e7'
         '4a64e3ee550e296bdde894f9202c6f372934cc29154f47d302599b4c368825a96a7b786faa6109a24a1101ff130fd9e4d0ccba094ec91e7f2ca645725bf71b34'
-        '437e0b0956576795087f9e5299f6b847aaaef8158847a269d34331d42da6729721d121eed82b95e4833f9d01322da677d85db924bf43140360c5592d51324565'
-        '2d69b0eb110f49badbf411ec22be0b10913321275d4146a9e3ea2e5a160a7388e6b0f70200d8ed8640c742f7791694a13be89d85f8424078396ab29e28fca113')
+        'b9472b3967c9d7549ee2bbf0180d919748b40b1f9a65b1c3789be40f62ed17a9d37c2020409f7835570620108bd5ec43e728966d075d66bf0b7261cdd36a60c3'
+        '95b083b842da6049a084ca015b7ddc099550aa818fc382d556cca832fee52265be568d20a2c50e70819aef6cf879e7a368f7dd3b5966356643b2efdd756e73f4')
 
 prepare() {
-  cp -r /usr/share/dotnet .
-
-  cd dotnet-source-build
-
-  [ -d patches/runtime ] || mkdir patches/runtime
-  cp ../9999-runtime-link-order.patch patches/runtime/
-  [ -d patches/sdk ] || mkdir patches/sdk
-  cp ../9999-sdk-telemetry-optout.patch patches/sdk/
-
-  # disable warnings
-  sed -i 's|skiptests|skiptests ignorewarnings|' repos/runtime.common.props
+  cd dotnet-installer
+  # fix bootstrap
+  git remote set-url origin https://github.com/dotnet/installer.git
 }
 
 pkgver() {
-  cd dotnet-source-build
+  cd dotnet-installer
 
-  if [[ $(git describe --tags) != v5.0.*-runtime ]]; then
+  if [[ $(git describe --tags) != v6.0.* ]]; then
+    echo "Invalid SDK version"
     exit 1
   fi
 
-  local _majorver=$(xmllint --xpath "//*[local-name()='MajorVersion']/text()" eng/Versions.props)
-  local _minorver=$(xmllint --xpath "//*[local-name()='MinorVersion']/text()" eng/Versions.props)
-  local _runtimever=$(xmllint --xpath "//*[local-name()='RuntimePatchVersion']/text()" eng/Versions.props)
-  local _sdkver=$(xmllint --xpath "//*[local-name()='SdkPatchVersion']/text()" eng/Versions.props)
+  local _standardver=$(xmllint --xpath "//*[local-name()='NETStandardLibraryRefPackageVersion']/text()" eng/Versions.props)
 
-  echo "${_majorver}.${_minorver}.${_runtimever}.sdk${_sdkver}"
+  if [[ $_standardver != 2.1.0 ]]; then
+    echo "Invalid Standard version"
+    exit 1
+  fi
+
+  local _sdkver=$(xmllint --xpath "//*[local-name()='VersionSDKMinor']/text()" eng/Versions.props)$(xmllint --xpath "//*[local-name()='VersionFeature']/text()" eng/Versions.props)
+  local _runtimever=$(xmllint --xpath "//*[local-name()='MicrosoftNETCoreAppRuntimewinx64PackageVersion']/text()" eng/Versions.props)
+
+
+  echo "${_runtimever}.sdk${_sdkver}"
 }
 
 build() {
-  cd dotnet-source-build
-
-  export SOURCE_BUILD_SKIP_SUBMODULE_CHECK=1
-
+  cd dotnet-installer
   ./build.sh \
-    --with-sdk ../dotnet \
-    /p:ArchiveDownloadedPackages=true \
-    /p:ContinueOnPrebuiltBaselineError=true \
-    /p:SkipPortableRuntimeBuild=true \
-    /p:SkipPrebuiltEnforcement=true \
-    /p:UseSystemLibraries=true \
-    /p:UseSystemLibunwind=true
+    /p:ArcadeBuildTarball=true \
+    /p:BuildPortableRuntime=false \
+    /p:BuildPortableSdk=false \
+    /p:TarballDir="${srcdir}"/sources \
+    /p:UseSystemLibraries=true
+  cd ../sources
+  pushd src/runtime.*
+  patch -Np1 -i ../../../dotnet-core-runtime-disable-package-validation.patch
+  popd
+  pushd src/sdk.*
+  patch -Np1 -i ../../../dotnet-core-sdk-telemetry-optout.patch
+  popd
+  ln -sf "${srcdir}"/Private.SourceBuilt.Artifacts.${_bootstrapver}.tar.gz packages/archive/
+  ./prep.sh
+  ./build.sh
 }
 
 package_dotnet-host() {
@@ -103,15 +109,17 @@ package_dotnet-host() {
     gcc-libs
     glibc
   )
+  optdepends=('bash-completion: Bash completion support')
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/{etc/profile.d,usr/{bin,lib,share/{dotnet,licenses/dotnet-host}}}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner dotnet host
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/licenses/dotnet-host/ --no-same-owner LICENSE.txt ThirdPartyNotices.txt
   ln -s /usr/share/dotnet/dotnet "${pkgdir}"/usr/bin/dotnet
   ln -s /usr/share/dotnet/host/fxr/${pkgver%.sdk*}/libhostfxr.so "${pkgdir}"/usr/lib/libhostfxr.so
-  install -Dm 644 ../../src/sdk.*/scripts/register-completions.bash "${pkgdir}"/usr/share/bash-completion/completions/dotnet
+  install -Dm 644 ../../../src/sdk.*/scripts/register-completions.bash "${pkgdir}"/usr/share/bash-completion/completions/dotnet
+  install -Dm 644 ../../../src/sdk.*/scripts/register-completions.zsh "${pkgdir}"/usr/share/zsh/site-functions/_dotnet
   install -Dm 644 ../../../../dotnet.sh -t "${pkgdir}"/etc/profile.d/
 }
 
@@ -128,11 +136,11 @@ package_dotnet-runtime() {
     openssl
   )
 
-  optdepends=('lttng-ust: CoreCLR tracing')
-  provides=(dotnet-runtime-5.0)
-  conflicts=(dotnet-runtime-5.0)
+  optdepends=('lttng-ust2.12: CoreCLR tracing')
+  provides=(dotnet-runtime-6.0)
+  conflicts=(dotnet-runtime-6.0)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner shared/Microsoft.NETCore.App
@@ -142,10 +150,10 @@ package_dotnet-runtime() {
 package_aspnet-runtime() {
   pkgdesc='The ASP.NET Core runtime'
   depends=(dotnet-runtime)
-  provides=(aspnet-runtime-5.0)
-  conflicts=(aspnet-runtime-5.0)
+  provides=(aspnet-runtime-6.0)
+  conflicts=(aspnet-runtime-6.0)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner shared/Microsoft.AspNetCore.App
@@ -162,10 +170,10 @@ package_dotnet-sdk() {
     netstandard-targeting-pack
   )
   optdepends=('aspnet-targeting-pack: Build ASP.NET Core applications')
-  provides=(dotnet-sdk-5.0)
-  conflicts=(dotnet-sdk-5.0)
+  provides=(dotnet-sdk-6.0)
+  conflicts=(dotnet-sdk-6.0)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner sdk templates
@@ -177,7 +185,7 @@ package_netstandard-targeting-pack() {
   provides=(netstandard-targeting-pack-2.1)
   conflicts=(netstandard-targeting-pack-2.1)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner packs/NETStandard.Library.Ref
@@ -187,10 +195,10 @@ package_netstandard-targeting-pack() {
 package_dotnet-targeting-pack() {
   pkgdesc='The .NET Core targeting pack'
   depends=(netstandard-targeting-pack)
-  provides=(dotnet-targeting-pack-5.0)
-  conflicts=(dotnet-targeting-pack-5.0)
+  provides=(dotnet-targeting-pack-6.0)
+  conflicts=(dotnet-targeting-pack-6.0)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner packs/Microsoft.NETCore.App.{Host.arch-x64,Ref}
@@ -200,10 +208,10 @@ package_dotnet-targeting-pack() {
 package_aspnet-targeting-pack() {
   pkgdesc='The ASP.NET Core targeting pack'
   depends=(dotnet-targeting-pack)
-  provides=(aspnet-targeting-pack-5.0)
-  conflicts=(aspnet-targeting-pack-5.0)
+  provides=(aspnet-targeting-pack-6.0)
+  conflicts=(aspnet-targeting-pack-6.0)
 
-  cd dotnet-source-build/artifacts/x64/Release
+  cd sources/artifacts/x64/Release
 
   install -dm 755 "${pkgdir}"/usr/share/{dotnet,licenses}
   bsdtar -xf dotnet-sdk-${pkgver%.*.sdk*}.${pkgver#*sdk}-arch-x64.tar.gz -C "${pkgdir}"/usr/share/dotnet/ --no-same-owner packs/Microsoft.AspNetCore.App.Ref
