db-move: moved python-gevent from [community-testing] to [community] (x86_64)
git-svn-id: file:///srv/repos/svn-community/svn@767957 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/repos/community-x86_64/PKGBUILD b/repos/community-x86_64/PKGBUILD
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -5,7 +5,7 @@
 pkgbase=python-gevent
 pkgname=(python-gevent python2-gevent)
 pkgver=20.9.0
-pkgrel=1
+pkgrel=3
 arch=('x86_64')
 pkgdesc="Python network library that uses greenlet and libev for easy and scalable concurrency"
 license=("MIT")
@@ -46,7 +46,7 @@ check() {
     export PYTHONPATH="$PYTHONPATH:/usr/lib/python3.6/site-packages"
     python setup.py install
     python -m gevent.tests
-  ) || warning "Tests failed"
+  ) || echo "Tests failed"
 
   (
     cd "$srcdir"/gevent-$pkgver-py2
@@ -55,7 +55,7 @@ check() {
     export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/site-packages"
     python setup.py install
     python2 -m gevent.tests
-  ) || warning "Tests failed"
+  ) || echo "Tests failed"
 }
 
 package_python-gevent() {
