db-move: moved hdf5-openmpi from [community-testing] to [community] (x86_64)
git-svn-id: file:///srv/repos/svn-community/svn@333172 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/repos/community-x86_64/PKGBUILD b/repos/community-x86_64/PKGBUILD
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -10,8 +10,8 @@
 _pkgname=hdf5
 _mpi=openmpi
 pkgname=${_pkgname}-${_mpi}
-pkgver=1.10.1
-pkgrel=4
+pkgver=1.10.2
+pkgrel=2
 pkgdesc="General purpose library and file format for storing scientific data (${_mpi} version)"
 arch=('x86_64')
 url="https://www.hdfgroup.org/HDF5/"
@@ -23,11 +23,15 @@ conflicts=('hdf5')
 replaces=("hdf5-fortran-${_mpi}")
 source=("https://support.hdfgroup.org/ftp/HDF5/releases/${_pkgname}-${pkgver:0:4}/${_pkgname}-${pkgver/_/-}/src/${_pkgname}-${pkgver/_/-}.tar.bz2"
         'mpi.patch')
-md5sums=('d89893c05ee7ea8611b51bb39450d64e'
+md5sums=('41fb9347801b546fba323523a1c1af51'
          'dfa8dd50b8a7ebb3ad7249c627156cf9')
+sha256sums=('1cad5b7bfdf128dfc53cd16fba48f6e7ae4e93c75c371d9ec8dfc4df0c1fcb71'
+            '603006358175b7a8b35fa44c484cddf45c0381cf50db4fb7c50ea5969d361eca')
 
 prepare() {
     cd ${_pkgname}-${pkgver/_/-}
+    # Fix building with GCC 8.1
+    sed 's/\(.*\)(void) HDF_NO_UBSAN/HDF_NO_UBSAN \1(void)/' -i src/H5detect.c
 
     # FS#33343
     patch -p1 -i ../mpi.patch
@@ -58,21 +62,26 @@ build() {
     make
 }
 
-# Check are failing with error while loading shared libraries: libhdf5.so.101: cannot open shared object file: No such file or directory
-#check() {
-#    cd ${pkgname}-${pkgver/_/-}
-#    make check
-#}
+check() {
+    cd ${_pkgname}-${pkgver/_/-}
+    # Without this, checks are failing with messages like “error while loading shared libraries: libhdf5.so.101: cannot open shared object file: No such file or directory”
+    export LD_LIBRARY_PATH="${srcdir}"/${pkgname}-${pkgver/_/-}/src/.libs/
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/c++/src/.libs/
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/fortran/src/.libs/
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/hl/src/.libs/
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/hl/c++/src/.libs/
+    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"${srcdir}"/${pkgname}-${pkgver/_/-}/hl/fortran/src/.libs/
+    # This is a parallel build, they are always OpenMPI bugs
+    make check || warning "Tests failed"
+}
 
 package() {
     cd ${_pkgname}-${pkgver/_/-}
 
     make DESTDIR="${pkgdir}" install
 
-    rm -rf "${pkgdir}"/usr/lib/libdynlib*.so
-
-    install -dm755 "${pkgdir}"/usr/share/${_pkgname}
-    mv "${pkgdir}"/usr/share/{hdf5_examples,${_pkgname}/examples}
+    install -dm755 "${pkgdir}"/usr/share/doc/${_pkgname}
+    mv "${pkgdir}"/usr/share/{hdf5_examples,doc/${_pkgname}/examples}
 
     install -Dm644 COPYING "${pkgdir}"/usr/share/licenses/${_pkgname}/LICENSE
 }
