db-move: moved gpac from [community-testing] to [community] (x86_64)
git-svn-id: file:///srv/repos/svn-community/svn@61715 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/repos/community-x86_64/PKGBUILD b/repos/community-x86_64/PKGBUILD
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -2,34 +2,42 @@
 # Maintainer: Eric Bélanger <eric@archlinux.org>
 
 pkgname=gpac
-pkgver=0.4.5
-pkgrel=9
+pkgver=3824
+pkgrel=1
 pkgdesc="A multimedia framework based on the MPEG-4 Systems standard"
 arch=('i686' 'x86_64')
 url="http://gpac.sourceforge.net"
-depends=('wxgtk' 'libmad' 'faad2' 'ffmpeg' 'freeglut')
 license=('LGPL')
+depends=('ffmpeg' 'libjpeg' 'libpng' 'mesa')
+makedepends=('jack' 'a52dec' 'freetype2' 'libxv' 'faad2' 'libmad')
+optdepends=('jack: for jack support' 'a52dec: for A52 support'
+            'faad2: for AAC support' 'libmad: for mp3 support')
 options=('!makeflags')
-source=(http://downloads.sourceforge.net/sourceforge/${pkgname}/${pkgname}-${pkgver}.tar.gz
-        libpng14-infopp-null.patch openjpeg14.patch)
-sha1sums=('2ec03c1d7dc3f4d10c0f7b47696cc1e753a56fc8'
-          '00ba08808ec46ef6b8301ede26e500b3449253c1'
-          '95747ca98cdf0efc33ec776764401f5a83818ab5')
+source=(ftp://ftp.archlinux.org/other/community/${pkgname}/${pkgname}-${pkgver}.tar.xz)
+sha1sums=('bf7039c2585d539475babc7996851627efd7ec59')
+
+# source PKGBUILD && mksource
+mksource() {
+  [[ -x /usr/bin/svn ]] || (echo "svn not found. Install subversion." && return 1)
+  _svnver=$pkgver
+  _svntrunk="https://gpac.svn.sourceforge.net/svnroot/gpac/trunk/gpac"
+  _svnmod="$pkgname-$pkgver"
+  mkdir ${pkgname}-$pkgver
+  pushd ${pkgname}-$pkgver
+  svn co $_svntrunk --config-dir ./ -r $_svnver $_svnmod
+  echo "#define GPAC_SVN_REVISION	\"$_svnver\"" > ${pkgname}-$pkgver/include/gpac/version.h
+  find . -depth -type d -name .svn -exec rm -rf {} \;
+  tar -cJf ../${pkgname}-$pkgver.tar.xz ${pkgname}-$pkgver/*
+  popd
+}
 
 build() {
-  cd "${srcdir}/${pkgname}"
-  chmod +x configure
-  sed -i 's|--warn-common||' configure
-  sed -i 's#lib64#lib#g' configure
-  patch -p1 -i "${srcdir}/libpng14-infopp-null.patch"
-  patch -p1 -i "${srcdir}/openjpeg14.patch"
-	
-  export LDFLAGS=${LDFLAGS/,--as-needed/}
+  cd "${srcdir}/${pkgname}-${pkgver}"
   ./configure --prefix=/usr --mandir=/usr/share/man --X11-path=/usr --use-js=no
   make
 }
 
 package() {
-  cd "${srcdir}/${pkgname}"
+  cd "${srcdir}/${pkgname}-${pkgver}"
   make DESTDIR="${pkgdir}" install install-lib
 }
