upgpkg: python-nose-progressive 1.5.2-3: Updating maintainer info. Switching to non-makepkg internal print on failing tests.
git-svn-id: file:///srv/repos/svn-community/svn@563725 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/python-nose-progressive/trunk/PKGBUILD b/python-nose-progressive/trunk/PKGBUILD
--- a/python-nose-progressive/trunk/PKGBUILD
+++ b/python-nose-progressive/trunk/PKGBUILD
@@ -1,8 +1,9 @@
-# Maintainer: David Runge <dave@sleepmap.de>
+# Maintainer: David Runge <dvzrv@archlinux.org>
+
 _name=nose-progressive
 pkgname=python-nose-progressive
 pkgver=1.5.2
-pkgrel=2
+pkgrel=3
 pkgdesc="Give your tests a progress bar and smarter tracebacks in 3 lines"
 arch=('any')
 url="https://github.com/erikrose/nose-progressive"
@@ -22,8 +23,8 @@ build() {
 
 check() {
   cd "$pkgname-$pkgver"
-  export PYTHONPATH=build/lib:${PYTHONPATH}
-  nosetests noseprogressive || warning "Known failing test: https://github.com/erikrose/nose-progressive/issues/90"
+  export PYTHONPATH="build/lib:${PYTHONPATH}"
+  nosetests noseprogressive || echo "Known failing test: https://github.com/erikrose/nose-progressive/issues/90"
 }
 
 package() {
