archrelease: copy trunk to community-x86_64, community-i686
git-svn-id: file:///srv/repos/svn-community/svn@107237 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/tint2/repos/community-x86_64/PKGBUILD b/tint2/repos/community-x86_64/PKGBUILD
--- a/tint2/repos/community-x86_64/PKGBUILD
+++ b/tint2/repos/community-x86_64/PKGBUILD
@@ -1,14 +1,15 @@
 # $Id$
-# Maintainer:  Bartłomiej Piotrowski <nospam@bpiotrowski.pl>
+# Maintainer: Alexander Rødseth <rodseth@gmail.com>
+# Contributor: Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
 # Contributor: Blue Peppers <bluepeppers@archlinux.us>
 # Contributor: Stefan Husmann< stefan-husmann@t-online.de>
 
 pkgname=tint2
 pkgver=0.11
-pkgrel=6
+pkgrel=7
 pkgdesc='Basic, good-looking task manager for WMs'
-arch=('i686' 'x86_64')
-url="http://code.google.com/p/tint2/"
+arch=('x86_64' 'i686')
+url='http://code.google.com/p/tint2/'
 license=('GPL2')
 conflicts=('ttm-svn' 'tint')
 replaces=('tint')
@@ -16,21 +17,29 @@ depends=('gtk2' 'imlib2')
 optdepends=('pygtk: for tint2wizard')
 makedepends=('pygtk' 'cmake')
 provides=('tint')
-source=(http://tint2.googlecode.com/files/tint2-$pkgver.tar.bz2
-        add-power-now-support.patch
-        fix_defunct_processes.patch
-        middle_click_on_clock.patch)
+source=("http://tint2.googlecode.com/files/tint2-$pkgver.tar.bz2"
+        'add-power-now-support.patch'
+        'clock.patch'
+        'launcher_apps_dir-v2.patch'
+        'src-task-align.patch'
+        'zombie-fix.patch')
 md5sums=('6fc5731e7425125fa84a2add5cef4bff'
-         '6cfcad028f1bd2f69812167f5395f890'
-         'b3d052ac5ada81c56e36133b1ecdee8c'
-         'f7918d29a87422aab6fb9d922867d8f8')
+         '448beead6c9d44b864f99e08a027cb56'
+         'bc0bab2979dacff551a97bdf2c2fdedc'
+         '13218765dd684ae825967d3ffb4f4a75'
+         'f0d7f51ec8dbf2e7b6bcca942f0fd6c0'
+         'cdb83cd911e005a3529e5d1cd952a956')
 
 prepare() {
-  cd $pkgname-$pkgver
+  cd "$pkgname-$pkgver"
 
-  patch -Np0 -i ../add-power-now-support.patch
-  patch -Np0 -i ../fix_defunct_processes.patch
-  patch -Np0 -i ../middle_click_on_clock.patch
+  # Applying all patches, even some that only applies partially.
+  # Tint2 works fine with these, but a new release from upstream would be nice.
+  for f in ../*.patch; do
+    echo -e "--- ${f##*/} ---\n"
+    patch -Np1 -i $f && echo "${f##*/} OK!" || echo "${f##*/} FAILED!"
+    echo
+  done
 
   # python2 fix
   sed -i 's_#!/usr/bin/env python_#!/usr/bin/env python2_' src/tint2conf/tintwizard.py
@@ -38,13 +47,18 @@ prepare() {
 }
 
 build() {
-  cd $pkgname-$pkgver
+  cd "$pkgname-$pkgver"
 
-  cmake -DCMAKE_INSTALL_PREFIX=/usr .
+  mkdir -p build
+  cd build
+  cmake .. \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DENABLE_TINT2CONF=0
   make 
 }
 
 package() {
-  cd $pkgname-$pkgver
-  make DESTDIR="$pkgdir" install
+  make -C "$pkgname-$pkgver/build" DESTDIR="$pkgdir" install
 }
+
+# vim:set ts=2 sw=2 et:
