upgpkg: python-qiniu 7.9.0-2: remove unused dependency
git-svn-id: file:///srv/repos/svn-community/svn@1302767 9fca08f4-af9d-4005-b8df-a31f2cc04f65

diff --git a/python-qiniu/trunk/PKGBUILD b/python-qiniu/trunk/PKGBUILD
--- a/python-qiniu/trunk/PKGBUILD
+++ b/python-qiniu/trunk/PKGBUILD
@@ -2,13 +2,14 @@
 
 pkgname=python-qiniu
 pkgver=7.9.0
-pkgrel=1
+pkgrel=2
 pkgdesc="Qiniu Resource Storage SDK for Python"
 arch=('any')
 url='https://github.com/qiniu/python-sdk'
 license=('MIT')
-depends=('python-requests' 'python-setuptools')
-checkdepends=('python-pytest-runner')
+depends=('python-requests')
+makedepends=('python-setuptools')
+checkdepends=('python-pytest' 'python-freezegun')
 source=("$pkgname-$pkgver.tar.gz::https://github.com/qiniu/python-sdk/archive/v$pkgver.tar.gz")
 sha512sums=('ddf0e2506c66b86822e05566a985961f5f22a7c0d4d8faeedbff2b1c96430c74fad3329a6dfb614cfcf68bd6c9ca308382d6a10b1cc9e0b82d277b1a89501d08')
 
@@ -18,18 +19,13 @@ build() {
 }
 
 check() {
-  # Extracted from .travis.yml
-  export QINIU_TEST_BUCKET="pythonsdk"
-  export QINIU_TEST_DOMAIN="pythonsdk.qiniudn.com"
-  export QINIU_TEST_ENV="travis"
-
   cd python-sdk-$pkgver
-  python setup.py pytest || echo "Tests failed"
+  pytest || echo "Tests failed"
 }
 
 package() {
   cd python-sdk-$pkgver
   python setup.py install -O1 --root "$pkgdir"
 
-  install -Dm644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
+  install -Dm644 LICENSE -t "$pkgdir"/usr/share/licenses/$pkgname/
 }
